// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbK2pAfeg8kcbjWr2tU_ycRLSu4WeHomg',
    appId: '1:1058761588240:web:7a815d6b08c9091e4cd495',
    messagingSenderId: '1058761588240',
    projectId: 'lokerku-apps',
    authDomain: 'lokerku-apps.firebaseapp.com',
    storageBucket: 'lokerku-apps.firebasestorage.app',
    measurementId: 'G-ZSTW9LSTP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5gmWqkYIssBZfYOA8BEl7ROk-jSsFLPo',
    appId: '1:1058761588240:android:0c72ea4d784dbd314cd495',
    messagingSenderId: '1058761588240',
    projectId: 'lokerku-apps',
    storageBucket: 'lokerku-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_4VzNGvIpMs-1aoZan7MtAD_D-Jx5Ck',
    appId: '1:1058761588240:ios:762ef0be5e4d9a6f4cd495',
    messagingSenderId: '1058761588240',
    projectId: 'lokerku-apps',
    storageBucket: 'lokerku-apps.firebasestorage.app',
    iosClientId: '1058761588240-d3in37kdj47imrpc0tk3gged132lurpn.apps.googleusercontent.com',
    iosBundleId: 'com.rulyoctareza.lokerkuApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_4VzNGvIpMs-1aoZan7MtAD_D-Jx5Ck',
    appId: '1:1058761588240:ios:762ef0be5e4d9a6f4cd495',
    messagingSenderId: '1058761588240',
    projectId: 'lokerku-apps',
    storageBucket: 'lokerku-apps.firebasestorage.app',
    iosClientId: '1058761588240-d3in37kdj47imrpc0tk3gged132lurpn.apps.googleusercontent.com',
    iosBundleId: 'com.rulyoctareza.lokerkuApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbK2pAfeg8kcbjWr2tU_ycRLSu4WeHomg',
    appId: '1:1058761588240:web:72596118b3fee2564cd495',
    messagingSenderId: '1058761588240',
    projectId: 'lokerku-apps',
    authDomain: 'lokerku-apps.firebaseapp.com',
    storageBucket: 'lokerku-apps.firebasestorage.app',
    measurementId: 'G-CRLQG60FCC',
  );

}